import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SONDER FlORIST COMPANY</title>
        <meta name="description" content="Generated by josh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex min-h-screen max-w-7xl mx-auto px-6 sm:px-10 items-end -mt-32 sm:-mt-56">
          <div className="font-serif text-5xl sm:text-6xl w-3/4 sm:w-1/2 leading-tight">
            <h1>The world’s first NFT verified clothing brand. </h1>
            {/* <a className="text-lg leading-1 font-sans">Shop Now</a> */}

            {/* clothing section */}
          </div>
        </div>
        <div
          id="shop"
          className="max-w-7xl mx-auto px-6 mb-16 sm:px-10 mt-32 flex items-center justify-center font-mono"
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-16">
            <div className="flex flex-col items-center">
              <div className="bg-slate-50 h-full w-72"></div>
              <h3 className="pt-6">Sonder "Worked Up" Hoodie</h3>
              <p>$110.00</p>
            </div>
            <div className="flex flex-col items-center">
              <div className="bg-slate-50 h-96 w-72"></div>
              <h3 className="pt-6">Sonder "Worked Up" Hoodie</h3>
              <p>$110.00</p>
            </div>
            <div className="flex flex-col items-center">
              <div className="bg-slate-50 h-96 w-72"></div>
              <h3 className="pt-6">Sonder "Worked Up" Hoodie</h3>
              <p>$110.00</p>
            </div>
            <div className="flex flex-col items-center">
              <div className="bg-slate-50 h-96 w-72"></div>
              <h3 className="pt-6">Sonder "Worked Up" Hoodie</h3>
              <p>$110.00</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
