import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import Link from "next/link";
import Product from "../components/Product";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SONDER FLORIST COMPANY</title>
        <meta name="description" content="Generated by josh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex min-h-screen max-w-7xl mx-auto px-6 sm:px-10 items-center justify-center">
          <div className="font-serif text-6xl md:text-7xl text-center -mt-48">
            <h1>The world&#39;s first NFT</h1>
            <h1> verified clothing brand. </h1>
            <a href="#shop" className="text-sm sm:text-md font-mono">
              Peruse the Collection
            </a>
          </div>
        </div>
        {/* clothing section */}
        <div
          id="shop"
          className="max-w-7xl mx-auto px-6 mb-16 sm:px-10 -mt-48 sm:-mt-52 flex items-center justify-center font-mono"
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-16 gap-y-20">
            <Product
              title="OF-COURSE Tee"
              description="Made to look like a 4 year old made it, but its Picasso the
                    4 year old. One size fits all."
              price="$39.00"
              image="/teefront.png"
              dink="/tee"
            />
            <Product
              title="OVERDONE Hoodie"
              description="Made to look like a 4 year old made it, but its Picasso the
                    4 year old. One size fits all."
              price="$89.00"
              image="/hoodiefront.png"
              dink="/hoodie"
            />
            <Product
              title="SORREY Long Tee"
              description="Made to look like a 4 year old made it, but its Picasso the
                    4 year old. One size fits all."
              price="$69.00"
              image="/longteefront.png"
              dink="/longtee"
            />
            <Product
              title="SAPPEY Tracks"
              description="Made to look like a 4 year old made it, but its Picasso the
                    4 year old. One size fits all."
              price="$79.00"
              image="/tracksfront.png"
              dink="/tracks"
            />
          </div>
        </div>
      </main>
    </div>
  );
}
